eports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'

autofetch_sources: True


networks:
  default: kovan
  kovan:
    link: '0xa36085F69e2889c224210F603D836748e7dC0088'

project_structure:
  build: ../next/abis

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}